[workspace]
members = [
    "crates/anvil/",
    "crates/anvil/core/",
    "crates/anvil/rpc/",
    "crates/anvil/server/",
    "crates/cast/",
    "crates/cheatcodes/",
    "crates/cheatcodes/spec/",
    "crates/chisel/",
    "crates/cli/",
    "crates/common/",
    "crates/config/",
    "crates/debugger/",
    "crates/doc/",
    "crates/evm/core/",
    "crates/evm/coverage/",
    "crates/evm/evm/",
    "crates/evm/fuzz/",
    "crates/evm/traces/",
    "crates/fmt/",
    "crates/forge/",
    "crates/script-sequence/",
    "crates/macros/",
    "crates/test-utils/",
]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2021"
# Remember to update clippy.toml as well
rust-version = "1.83"
authors = ["Foundry Contributors"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/foundry-rs/foundry"
repository = "https://github.com/foundry-rs/foundry"
exclude = ["benches/", "tests/", "test-data/", "testdata/"]

[workspace.lints.clippy]
dbg-macro = "warn"
manual-string-new = "warn"
uninlined-format-args = "warn"
use-self = "warn"
redundant-clone = "warn"
octal-escapes = "allow"

[workspace.lints.rust]
rust-2018-idioms = "warn"
# unreachable-pub = "warn"
unused-must-use = "warn"
redundant-lifetimes = "warn"

[workspace.lints.rustdoc]
all = "warn"

# Speed up compilation time for dev builds by reducing emitted debug info.
# NOTE: Debuggers may provide less useful information with this setting.
# Uncomment this section if you're using a debugger.
[profile.dev]
# https://davidlattimore.github.io/posts/2024/02/04/speeding-up-the-rust-edit-build-run-cycle.html
debug = "line-tables-only"
split-debuginfo = "unpacked"

[profile.release]
opt-level = 3
lto = "thin"
debug = "line-tables-only"
strip = "debuginfo"
panic = "abort"
codegen-units = 16

# Use the `--profile profiling` flag to show symbols in release mode.
# e.g. `cargo build --profile profiling`
[profile.profiling]
inherits = "release"
debug = 2
split-debuginfo = "unpacked"
strip = false

[profile.bench]
inherits = "profiling"

[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1

# Speed up tests and dev build.
[profile.dev.package]
# Solc and artifacts
foundry-compilers.opt-level = 3
solang-parser.opt-level = 3
lalrpop-util.opt-level = 3
serde_json.opt-level = 3

# EVM
alloy-dyn-abi.opt-level = 3
alloy-json-abi.opt-level = 3
alloy-primitives.opt-level = 3
alloy-sol-type-parser.opt-level = 3
alloy-sol-types.opt-level = 3
hashbrown.opt-level = 3
keccak.opt-level = 3
revm-interpreter.opt-level = 3
revm-precompile.opt-level = 3
revm-primitives.opt-level = 3
revm.opt-level = 3
ruint.opt-level = 3
sha2.opt-level = 3
sha3.opt-level = 3
tiny-keccak.opt-level = 3
bitvec.opt-level = 3

# fuzzing
proptest.opt-level = 3
foundry-evm-fuzz.opt-level = 3

# forking
axum.opt-level = 3

# keystores
scrypt.opt-level = 3

# Override packages which aren't perf-sensitive for faster compilation speed and smaller binary size.
[profile.release.package]
alloy-sol-macro-expander.opt-level = "z"
figment.opt-level = "z"
foundry-compilers-artifacts-solc.opt-level = "z"
foundry-config.opt-level = "z"
html5ever.opt-level = "z"
mdbook.opt-level = "z"
prettyplease.opt-level = "z"
protobuf.opt-level = "z"
pulldown-cmark.opt-level = "z"
syn-solidity.opt-level = "z"
syn.opt-level = "z"
trezor-client.opt-level = "z"

[workspace.dependencies]
anvil = { path = "crates/anvil" }
cast = { path = "crates/cast" }
chisel = { path = "crates/chisel" }
forge = { path = "crates/forge" }

forge-doc = { path = "crates/doc" }
forge-fmt = { path = "crates/fmt" }
forge-verify = { path = "crates/verify" }
forge-script = { path = "crates/script" }
forge-sol-macro-gen = { path = "crates/sol-macro-gen" }
forge-script-sequence = { path = "crates/script-sequence" }
foundry-cheatcodes = { path = "crates/cheatcodes" }
foundry-cheatcodes-spec = { path = "crates/cheatcodes/spec" }
foundry-cli = { path = "crates/cli" }
foundry-common = { path = "crates/common" }
foundry-common-fmt = { path = "crates/common/fmt" }
foundry-config = { path = "crates/config" }
foundry-debugger = { path = "crates/debugger" }
foundry-evm = { path = "crates/evm/evm" }
foundry-evm-abi = { path = "crates/evm/abi" }
foundry-evm-core = { path = "crates/evm/core" }
foundry-evm-coverage = { path = "crates/evm/coverage" }
foundry-evm-fuzz = { path = "crates/evm/fuzz" }
foundry-evm-traces = { path = "crates/evm/traces" }
foundry-macros = { path = "crates/macros" }
foundry-test-utils = { path = "crates/test-utils" }
foundry-wallets = { path = "crates/wallets" }
foundry-linking = { path = "crates/linking" }

# solc & compilation utilities
foundry-block-explorers = { version = "0.9.0", default-features = false }
foundry-compilers = { version = "0.12.8", default-features = false }
foundry-fork-db = "0.9.0"
solang-parser = "=0.3.3"
solar-ast = { version = "=0.1.1", default-features = false }
solar-parse = { version = "=0.1.1", default-features = false }
solar-interface = "=0.1.1"

## revm
# no default features to avoid c-kzg
revm = { version = "18.0.0", default-features = false }
revm-primitives = { version = "14.0.0", features = ["std", "serde"] }
revm-inspectors = { version = "0.13.0", features = ["serde"] }

## ethers
ethers-contract-abigen = { version = "2.0.14", default-features = false }

## alloy
alloy-consensus = { version = "0.8.0", default-features = false }
alloy-contract = { version = "0.8.0", default-features = false }
alloy-eips = { version = "0.8.0", default-features = false }
alloy-genesis = { version = "0.8.0", default-features = false }
alloy-json-rpc = { version = "0.8.0", default-features = false }
alloy-network = { version = "0.8.0", default-features = false }
alloy-provider = { version = "0.8.0", default-features = false }
alloy-pubsub = { version = "0.8.0", default-features = false }
alloy-rpc-client = { version = "0.8.0", default-features = false }
alloy-rpc-types = { version = "0.8.0", default-features = true }
alloy-serde = { version = "0.8.0", default-features = false }
alloy-signer = { version = "0.8.0", default-features = false }
alloy-signer-aws = { version = "0.8.0", default-features = false }
alloy-signer-gcp = { version = "0.8.0", default-features = false }
alloy-signer-ledger = { version = "0.8.0", default-features = false }
alloy-signer-local = { version = "0.8.0", default-features = false }
alloy-signer-trezor = { version = "0.8.0", default-features = false }
alloy-transport = { version = "0.8.0", default-features = false }
alloy-transport-http = { version = "0.8.0", default-features = false }
alloy-transport-ipc = { version = "0.8.0", default-features = false }
alloy-transport-ws = { version = "0.8.0", default-features = false }
alloy-node-bindings = { version = "0.8.0", default-features = false }
alloy-network-primitives = { version = "0.8.0", default-features = false }

## alloy-core
alloy-dyn-abi = { version = "0.8.15", features = ["seismic", "std"] }
alloy-json-abi = { version = "0.8.15", features = ["seismic"] }
alloy-primitives = { version = "0.8.15", features = ["getrandom", "rand", "seismic"] }
alloy-sol-macro-expander = { version = "0.8.15", features = ["seismic"] }
alloy-sol-macro-input = { version = "0.8.15", features = ["seismic"] }
alloy-sol-types = { version = "0.8.15", features = ["seismic"] }
syn-solidity = { version = "0.8.15", features = ["seismic"] }

alloy-chains = "0.1"
alloy-rlp = "0.3"
alloy-trie = "0.7.0"

## op-alloy
op-alloy-rpc-types = "0.8.0"
op-alloy-consensus = "0.8.0"

## cli
anstream = "0.6"
anstyle = "1.0"
terminal_size = "0.4"

# macros
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
async-trait = "0.1"
derive_more = { version = "1.0", features = ["full"] }
thiserror = "2"

# bench
divan = "0.1"

# misc
auto_impl = "1"
bytes = "1.8"
walkdir = "2"
prettyplease = "0.2"
ahash = "0.8"
base64 = "0.22"
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "std",
] }
axum = "0.7"
color-eyre = "0.6"
comfy-table = "7"
dunce = "1"
evm-disassembler = "0.5"
evmole = "0.6"
eyre = "0.6"
figment = "0.10"
futures = "0.3"
hyper = "1.5"
indexmap = "2.6"
itertools = "0.13"
jsonpath_lib = "0.3"
k256 = "0.13"
mesc = "0.3"
num-format = "0.4"
parking_lot = "0.12"
proptest = "1"
rand = "0.8"
rayon = "1"
regex = { version = "1", default-features = false }
reqwest = { version = "0.12", default-features = false }
semver = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
similar-asserts = "1.6"
soldeer-commands = "=0.5.2"
strum = "0.26"
tempfile = "3.13"
tikv-jemallocator = "0.6"
tokio = "1"
toml = "0.8"
tower = "0.4"
tower-http = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2"
vergen = { version = "8", default-features = false }
yansi = { version = "1.0", features = ["detect-tty", "detect-env"] }

tee_service_api = { git = "ssh://git@github.com/SeismicSystems/TEEService.git", package = "tee_service_api", rev = "39b2865" }

[patch.crates-io]
# If our dependencies depend on these things,
# then this will override whatever versions they point to
# and instead use our local version
foundry-fork-db = { git = "ssh://git@github.com/SeismicSystems/seismic-foundry-fork-db.git", rev = "cd54596" }

# seismic-revm
revm = { git = "ssh://git@github.com/SeismicSystems/seismic-revm.git", rev = "39b4dea21beda3d9a693023f69c2f6b8a940d29e" }
revm-primitives = { git = "ssh://git@github.com/SeismicSystems/seismic-revm.git", rev = "39b4dea21beda3d9a693023f69c2f6b8a940d29e" }
revm-interpreter = { git = "ssh://git@github.com/SeismicSystems/seismic-revm.git", rev = "39b4dea21beda3d9a693023f69c2f6b8a940d29e" }

# seismic-revm-inspectors
revm-inspectors = { git = "ssh://git@github.com/SeismicSystems/seismic-revm-inspectors.git", rev = "19828b8" }

# seismic-alloy-core
alloy-dyn-abi = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy-core.git", rev = "6e1c0e9" }
alloy-json-abi = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy-core.git", rev = "6e1c0e9" }
alloy-primitives = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy-core.git", rev = "6e1c0e9" }
alloy-sol-macro = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy-core.git", rev = "6e1c0e9" }
alloy-sol-macro-expander = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy-core.git", rev = "6e1c0e9" }
alloy-sol-macro-input = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy-core.git", rev = "6e1c0e9" }
alloy-sol-types = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy-core.git", rev = "6e1c0e9" }
alloy-sol-type-parser = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy-core.git", rev = "6e1c0e9" }

alloy-consensus = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-contract = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-eips = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-genesis = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-json-rpc = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-network = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-provider = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-pubsub = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-rpc-client = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-rpc-types = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-rpc-types-trace = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-rpc-types-eth = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-serde = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-signer = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-signer-aws = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-signer-gcp = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-signer-ledger = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-signer-local = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-signer-trezor = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-transport = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-transport-http = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-transport-ipc = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-transport-ws = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-node-bindings = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
alloy-network-primitives = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy.git", rev = "cbd6fa1" }
