#!/usr/bin/env bash
set -eo pipefail

echo "Installing sfoundryup..."

# Define paths consistent with sfoundryup
BASE_DIR="${XDG_CONFIG_HOME:-$HOME}"
SEISMIC_DIR="${SEISMIC_DIR:-"$BASE_DIR/.seismic"}"
SEISMIC_BIN_DIR="$SEISMIC_DIR/bin"

BIN_PATH="$SEISMIC_BIN_DIR/sfoundryup"


# GitHub raw URL to sfoundryup
RAW_API_URL="https://raw.githubusercontent.com/SeismicSystems/seismic-foundry/seismic/sfoundryup/sfoundryup"

# Create necessary directories
mkdir -p "$SEISMIC_BIN_DIR"

# Download sfoundryup using GitHub raw content URL
echo "Fetching sfoundryup..."
curl -sSf "$RAW_API_URL" -o "$BIN_PATH"

# Make the file executable
chmod +x "$BIN_PATH"

# Update the PATH environment variable
case $SHELL in
*/zsh)
    PROFILE="${ZDOTDIR:-$HOME}/.zshenv"
    ;;
*/bash)
    PROFILE="$HOME/.bashrc"
    ;;
*/fish)
    PROFILE="$HOME/.config/fish/config.fish"
    ;;
*/ash)
    PROFILE="$HOME/.profile"
    ;;
*)
    echo "Could not detect shell. Please manually add $SEISMIC_BIN_DIR to your PATH."
    exit 1
esac

if [[ ":$PATH:" != *":$SEISMIC_BIN_DIR:"* ]]; then
    if [[ "$SHELL" == *fish ]]; then
        echo >> "$PROFILE" && echo "fish_add_path $SEISMIC_BIN_DIR" >> "$PROFILE"
    else
        echo >> "$PROFILE" && echo "export PATH=\"\$PATH:$SEISMIC_BIN_DIR\"" >> "$PROFILE"
    fi
fi

# Ensure prerequisites are installed
echo "Checking prerequisites..."
for cmd in git curl; do
    if ! command -v "$cmd" >/dev/null; then
        echo "Error: $cmd is required but not installed. Please install it and re-run this script."
        exit 1
    fi
done

# Print completion message
echo
echo "sfoundryup installed successfully at $SEISMIC_BIN_DIR/sfoundryup."
echo "Run 'source $PROFILE' or start a new terminal session to use sfoundryup."
echo "Then, run 'sfoundryup' to install Seismic Foundry tools."
